kg:
  url: https://kg.humanbrainproject.org
allen:
  url: http://api.brain-map.org/api/v2
connectivity:
  url: https://connectivityquery-connectivity.apps-dev.hbp.eu
server:
  error:
    whitelabel:
      enabled: true
spring:
  main:
    banner-mode: console
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false