kg:
  url: https://kg.humanbrainproject.org
allen:
  url: http://api.brain-map.org/api/v2
server:
  error:
    whitelabel:
      enabled: true
spring:
  main:
    show-banner: false
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false