kg:
  url: https://kg.humanbrainproject.eu
allen:
  url: http://api.brain-map.org/api/v2
connectivity:
  url: https://connectivityquery-connectivity.apps-dev.hbp.eu
server:
  error:
    whitelabel:
      enabled: true
spring:
  main:
    banner-mode: console
  hateoas:
    use-hal-as-default-json-media-type: true
  mvc:
    favicon:
      enabled: false
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: ["health", "info", "metrics"]
